### ISSUE TITLE
Use Dialog from @angular/cdk/dialog instead of MatDialog from @angular/material

### ISSUE THREAD

**Issue by TempleOfTemplar** [Zaroymi/ngx-url-modal#1]
Hi! First of all, I want to say a huge thank you for this library!
I implemented something similar in my project, and I am very glad that now a similar solution exists as a package. 
Would like to suggest using `Dialog` from [@angular/cdk/dialog](https://material.angular.io/cdk/dialog/overview) instead of `MatDialog` from [@angular/material/dialog](https://material.angular.io/components/dialog/overview).

**Comment by Zaroymi** [comment]
Hi!
Thank you for your feedback! 
I've checked links and it's really nice suggestion to change `MatDialog` to `Dialog`. 
Will do this asap

**Comment by Zaroymi** [comment]
How It should be works with `Dialog` and `MatDialog`
